project:
  type: website
  output-dir: docs
  
website:
  title: "Analyzing satellite image collections on public cloud platforms with R"
  reader-mode: false
  search: false
  navbar:
    background: "#546e7a"
    foreground: "#ffffff"
    right:
      - icon: github
        href: https://github.com/appelmar/CONAE_2022
        aria-label: GitHub
    left:
      - text: "Slides"
        href: introduction.qmd
      - text: "Example 1"
        href: ex01.qmd
      - text: "Example 2"
        href: ex02.qmd
      - text: "Example 3"
        href: ex03.qmd
  page-footer:
    background: "#546e7a"
    # center: 
    #   - text: "Top"
    #     href: "´#top"
    right:
      - text: "&#169; 2022 Marius Appel, <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"
      
execute:
  freeze: auto  # re-render only when source changes
  warning: false
  
  
bibliography: references.bib
csl: american-statistical-association.csl
citations-hover: true
knitr:
  opts_chunk: 
    #collapse: true
    comment: "##"
    results: "hold"
format: 
  html:
    theme: [zephyr, theme.scss]
    #self-contained: true
    toc: true
    toc-location: left
    toc-title: Contents
    title-block-categories: false
    
    #monofont: "Roboto Mono"
    #mainfont: "Roboto"
    code-tools: true
    code-link: false
    highlight-style: arrow
    #title-block-banner: "#546e7a"
    #title-block-banner-color: "white"
    code-block-bg: true
    code-block-background: true
    code-block-border-left: true
    #code-overflow: "wrap"
    fontsize: 10pt
    code-overflow: "scroll"
    #code-line-numbers: true

    